name: Flutter Build

on:
  push:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Doctor
        run: flutter doctor

      - name: Archive iOS app
        run: |
          flutter build ios --release --no-codesign

      - name: Make ipa file
        run: |
          ls build/ios/iphoneos/
          mkdir Payload
          cp -r build/ios/iphoneos/Runner.app Payload/Runner.app
          zip -r flutter_application_2.ipa Payload

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: flutter_application_2.ipa

  build-android-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (Ninja, CMake)
        run: |
          sudo apt update
          sudo apt install -y ninja-build cmake

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Doctor
        run: |
          flutter doctor
          yes | flutter doctor --android-licenses

      - name: Build APK
        run: |
          flutter build apk --release

      - name: Build linux
        run: |
          flutter build linux --release
          ls build/linux/

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk-build
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            README.md

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: |
            build/linux/x64/release/bundle/
